### ISSUE TITLE
Good news to "inheritance effector" node!

### ISSUE THREAD

**Issue by kdsin23** [harisreedhar/AN_BLUEFOX#11]
i found another way to create curve option in inheritance effector,it can performance there times faster than before:
![curve 2](https://user-images.githubusercontent.com/64368228/80920443-87c0cf80-8da2-11ea-995c-4219e82ba488.gif)

in my test, 1000000 points only needs 4.9s ,but at the same points numbers needs16s before, you can try it if you will.

**Comment by harisreedhar** [comment]
> i found another way to create curve option in inheritance effector,it can performance there times faster than before:
> ![curve 2](https://user-images.githubusercontent.com/64368228/80920443-87c0cf80-8da2-11ea-995c-4219e82ba488.gif)
> 
> in my test, 1000000 points only needs 4.9s ,but at the same points numbers needs16s before, you can try it if you will.

Great ! will try this method, thanks a lot for sharing. Do you have twitter account?

**Comment by harisreedhar** [comment]
> i found another way to create curve option in inheritance effector,it can performance there times faster than before:
> ![curve 2](https://user-images.githubusercontent.com/64368228/80920443-87c0cf80-8da2-11ea-995c-4219e82ba488.gif)
> 
> in my test, 1000000 points only needs 4.9s ,but at the same points numbers needs16s before, you can try it if you will.
![curveinterpolation alternate setup](https://user-images.githubusercontent.com/46858047/80986502-4685f980-8e4e-11ea-8100-2fbffe832421.png)
Slightly modified your setup. is this okay?

**Comment by kdsin23** [comment]
> > ![curveinterpolation alternate setup](https://user-images.githubusercontent.com/46858047/80986502-4685f980-8e4e-11ea-8100-2fbffe832421.png)
> > Slightly modified your setup. is this okay?

OK,it is nice to modify it. i guess you may add the radius of the spline to effect the locations of the points in the next build,what do you think?

**Comment by harisreedhar** [comment]
> 
> > > ![curveinterpolation alternate setup](https://user-images.githubusercontent.com/46858047/80986502-4685f980-8e4e-11ea-8100-2fbffe832421.png)
> > > Slightly modified your setup. is this okay?
> 
> OK,it is nice to modify it. i guess you may add the radius of the spline to effect the locations of the points in the next build,what do you think?
> 
> 

Radius to affect what? Scale of random vector ?

**Comment by kdsin23** [comment]
> > > > ![curveinterpolation alternate setup](https://user-images.githubusercontent.com/46858047/80986502-4685f980-8e4e-11ea-8100-2fbffe832421.png)
> > > > Slightly modified your setup. is this okay?
> > 
> > 
> > OK,it is nice to modify it. i guess you may add the radius of the spline to effect the locations of the points in the next build,what do you think?
> 
> Radius to affect what? Scale of random vector ?

yes,yes

**Comment by harisreedhar** [comment]
Hi I have added Matrix Option to inheritance effector. Performance also improved a lot. Option for spline radius not added yet. ☺Thank you.

![inheritance-matrix](https://user-images.githubusercontent.com/46858047/81736473-445a1580-94b4-11ea-8281-6398b99023a3.png)

![inheritance-improvement](https://user-images.githubusercontent.com/46858047/81736492-4ae88d00-94b4-11ea-96e3-a93a2eb858da.png)

**Comment by kdsin23** [comment]
> Hi I have added Matrix Option to inheritance effector in [335d5af](https://github.com/harisreedhar/AN_BLUEFOX/commit/335d5afb0abbfc09d97b93db47039abea96aa1fd). Performance also improved a lot. Option for spline radius not added yet. relaxedThank you.


Oh,nice!you are great! i think the performance is much much better than before version.

**Comment by harisreedhar** [comment]
> > improved a lot. Option for spline radius not added yet. relaxedThank you.
> 
> Oh,nice!you are great! i think the performance is much much better than before version.

Yeah, The mix vectorlist method improved performance a lot.
