### ISSUE TITLE
QUESTION - Will the spline tracer, and the rest of new nodes, be implemented in AN master?

### ISSUE THREAD

**Issue by juangea** [harisreedhar/AN_BLUEFOX#16]
Hi there.

That's the question.

The spline tracer node seems interesting, usually i use the graphicall version of Animation Nodes, which is based in latest master changes, will your nodes be implemented there at some point?

Thanks!

**Comment by harisreedhar** [comment]
Hi juangea, I really like to see these nodes on master, but not sure when. Spline tracer have some limitations it has some issues when using inside loop. similarly some other nodes also have issues. i'm still learning. once i'm happy with the code i'll make request on the master.

**Comment by juangea** [comment]
Thanks for the info! :)
