### ISSUE TITLE
Spline Tracer

### ISSUE THREAD

**Issue by harisreedhar** [harisreedhar/AN_BLUEFOX#4]
![tracegif](https://user-images.githubusercontent.com/46858047/80310913-9a636380-87fa-11ea-86e0-89c1051d65c0.gif)

![star trail](https://user-images.githubusercontent.com/46858047/80310901-8f103800-87fa-11ea-9cc9-23ee88d808ae.png)

**Comment by kdsin23** [comment]
The "Spline Tracer Node" is very useful! that is great!
