### ISSUE TITLE
Is it possible to add a Random Color Node to AN?

### ISSUE THREAD

**Issue by kdsin23** [harisreedhar/AN_BLUEFOX#6]
HI,random color has been used high frequency,always need creat a lot of nodes to achieve,as the shot
![shot2](https://user-images.githubusercontent.com/64368228/80344781-b74f7380-889a-11ea-86c8-366859b4fe4f.png)

so i write a python code to achieve it,but it is very slow when it executed, 100000 colors need 211ms
![shot1](https://user-images.githubusercontent.com/64368228/80345149-465c8b80-889b-11ea-8624-989b1d06bd1d.png)
i heared the cython code can speed up the performance,but i can't write a  cython.code

**Comment by harisreedhar** [comment]
I think cython would speed up things, especially when using for loops. or you can use numpy it also helps to speedup things.

**Comment by kdsin23** [comment]
> I think cython would speed up things, especially when using loops. or you can use numpy it also helps to speedup things.

I forgot to attach my code file ,this is my code ,please help me to speed up things,you can change .txt to .py,Thank you!

[mesh Islands_vertex color.txt](https://github.com/harisreedhar/AN_BLUEFOX/files/4539030/mesh.Islands_vertex.color.txt)

**Comment by harisreedhar** [comment]
> > I think cython would speed up things, especially when using loops. or you can use numpy it also helps to speedup things.
> 
> I forgot to attach my code file ,this is my code ,please help me to speed up things,Thank you!
> 
> [random_color.py.zip](https://github.com/harisreedhar/AN_BLUEFOX/files/4539063/random_color.py.zip)

Hi i have checked your code, loops are slow in python compared to cython, so u need to write code in cython to get maximum speed. I have tried to generate random number using numpy which slightly improved speed.

Here is the code using Numpy:
```
import bpy
import random
import numpy as np
from bpy.props import *
from ... events import propertyChanged
from ... base_types import AnimationNode
from ... data_structures import Color, ColorList

class NumpyRandomColors(bpy.types.Node, AnimationNode):
    bl_idname = "an_NumpyRandomColors"
    bl_label = "Numpy Random Colors"

    nodeSeed: IntProperty(name = "Node Seed", update = propertyChanged, max = 1000, min = 0)

    createList: BoolProperty(name = "Create List", default = False,
        description = "Create a list of random colors",
        update = AnimationNode.refresh)

    def setup(self):
        self.randomizeNodeSeed()    

    def create(self):
        if self.createList:
            self.newInput("Integer", "Count", "count", value = 5, minValue = 0)
            self.newInput("Integer", "Seed", "seed")
            self.newOutput("Color List", "Colors", "randomColors")
        else:
            self.newInput("Integer", "Seed", "seed")
            self.newOutput("Color", "Color", "color")

    def draw(self, layout):
        row = layout.row(align = True)
        row.prop(self, "nodeSeed", text = "Node Seed")
        row.prop(self, "createList", text = "", icon = "LINENUMBERS_ON") 

    def getExecutionFunctionName(self):
        if self.createList:
            return "execute_List"
        else:
            return "execute_Single"       
                   
    def execute_Single(self, seed):
        finalSeed = seed + 25642 * self.nodeSeed
        np.random.seed(finalSeed)
        rgb = np.random.random_sample((1, 3))
        np.clip(rgb, 0, 1)
        return Color((rgb[0][0], rgb[0][1], rgb[0][2], 1))

    def execute_List(self, count, seed):
        finalSeed = seed + 25642 * self.nodeSeed
        np.random.seed(finalSeed)
        rgba = np.random.random_sample((count, 4))
        rgba[:,-1] = 1 #set alpha to 1
        np.clip(rgba, 0, 1) #clip value between 0 and 1
        return ColorList.fromValues(np.absolute(rgba))

    def duplicate(self, sourceNode):
        self.randomizeNodeSeed()

    def randomizeNodeSeed(self):
        self.nodeSeed = int(random.random() * 100)       
        
```
Speed improvement is quite noticeable :

![numpyvspython](https://user-images.githubusercontent.com/46858047/80382984-9e59b900-88c0-11ea-8ebe-f12ab3412c34.png)

**Comment by harisreedhar** [comment]
![cythonizedrandom](https://user-images.githubusercontent.com/46858047/80395706-3a8bbc00-88d1-11ea-938f-d138c1ca167a.PNG)

Added Cythonized Random color node 18fab0c4b5f7148b90cc097aca9da6c5d3c2b91e

**Comment by kdsin23** [comment]
> ![cythonizedrandom](https://user-images.githubusercontent.com/46858047/80395706-3a8bbc00-88d1-11ea-938f-d138c1ca167a.PNG)
> 
> Added Cythonized Random color node

Thank you very much! you are awsome!
by the way,where to learn cython code and python numpy?
would you mind giving me some links, Thank you!

**Comment by harisreedhar** [comment]
> > ![cythonizedrandom](https://user-images.githubusercontent.com/46858047/80395706-3a8bbc00-88d1-11ea-938f-d138c1ca167a.PNG)
> > Added Cythonized Random color node
> 
> Thank you very much! you are awsome!
> by the way,where to learn cython code and python numpy?
> would you mind giving me some links, Thank you!

You're welcome. I don't really found any good cython resources online, stackoverflow helped me a lot in learning cython. It's quite easy to convert python code to cython...only difference i noticed in cython is that we need to specify type information. In Animation nodes cython functions are written in `.pyx` file and then called using python. 
for example in python we declare a integer variable as,
`x = 5`
while in cython,
`cdef int x = 5`
you can write all python codes in cython just provide type that's it. may be i'm wrong i'm still noob😁.
For numpy i really recommend this [video](https://youtu.be/GB9ByFAIAH4).
Also see [documentation](https://numpy.org/doc/1.18/):
