### ISSUE TITLE
how to use "Memory Node"?

### ISSUE THREAD

**Issue by kdsin23** [harisreedhar/AN_BLUEFOX#7]
hi,i don't know how to use the memory node you developed ,could you provide a Example about it?thank you!

**Comment by harisreedhar** [comment]
> hi,i don't know how to use the memory node you developed ,could you provide a Example about it?thank you!

Hi,This node is similar to [Memory node](https://help.maxon.net/us/index.html#GVMEMORY) of c4d. It stores all previous state of input in a list. Currently it have two modes `Use frame` and `Custom`. Working of `Use frame` is similar to spline tracer it will append data to a list on every execution and clears data from the list on `resetframe`. `Custom` mode on the otherhand let's you to decide when to append and clear the list using boolean inputs.

Here is a simple example of storing a mesh as data in memory node:
![memory-nodeex1](https://user-images.githubusercontent.com/46858047/80358522-309a9680-889a-11ea-90c9-67a0fa9b994a.gif)

This node is still in development stage, i'll add more examples soon.😊
